framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_secure: auto
    default_locale: en
    csrf_protection: true
    form: true
    translator:
        default_path: '%kernel.project_dir%/translations'
    validation: { enabled: true }
    templating:
        engines: ['twig']